services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  HDNET\Focuspoint\:
    resource: '../Classes/*'

  HDNET\Focuspoint\EventListener\ProcessFileListActionsEventListener:
    tags:
      - name: event.listener
        identifier: 'FocuspointProcessFileListActionsEventListener'
        event: TYPO3\CMS\Filelist\Event\ProcessFileListActionsEvent

  HDNET\Focuspoint\EventListener\ModifyFileReferenceControlsEventListener:
    tags:
      - name: event.listener
        identifier: 'FocuspointModifyFileReferenceControlsEventListener'
        event: TYPO3\CMS\Backend\Form\Event\ModifyFileReferenceControlsEvent
